### ISSUE TITLE
When changing the property the slug is based on, slug itself does not update

### ISSUE THREAD

**Issue by tommhuth** [qqilihq/mongoose-slugger#23]
Like the title says, is this not supported?

```ts
const trip = await Trip.findOne({ _id: id, owner: userId }).exec()
trip.title = data.title
trip.description = data.description

await trip.save()
```

The slug remains the same.

**Comment by qqilihq** [comment]
Yes, that’s intended. We want slugs to be immutable for our use case. It could probably be a configurable option.

**Comment by tommhuth** [comment]
That would be very useful, since the slug is supposed to represent the content it is used for: If the title of the blog post changes, it makes no sense to keep the old slug.

**Comment by qqilihq** [comment]
Point taken! I’m open for a MR which allows this as an opt-in feature!

**Comment by k2xl** [comment]
Was this ever added?

**Comment by qqilihq** [comment]
No
