### ISSUE TITLE
(Error Code 11000) How to create slug with exists documents

### ISSUE THREAD

**Issue by KatonyVN** [qqilihq/mongoose-slugger#32]
Hello friends!
I am facing a problem when using with Typegoose, I am trying to allow users to create the same documents, but when using this plugin, I am getting error code 11000 when creating the document I am creating already existed before.
Here is my code, if I'm wrong please help me
Model.ts
![image](https://user-images.githubusercontent.com/96916378/150637466-997ecc47-5b76-40a6-bb1d-4c381470c581.png)

Error message:
![image](https://user-images.githubusercontent.com/96916378/150637482-3db37859-f119-489c-99bb-46447b6d1a0e.png)

Thank all!

**Comment by qqilihq** [comment]
1. Generally, the `title` should not be in the unique index, the `slug` would be sufficient.

2. If this does not help, please provide a test case here (without Typegoose, just plain Mongoose)
