### ISSUE TITLE
Non-Unique Slug Generation Issue

### ISSUE THREAD

**Issue by Nziranziza** [qqilihq/mongoose-slugger#55]
# Description:
### Issue:
I have encountered an issue with the "mongoose-slugger-plugin" where slugs are not being generated as expected. The plugin is supposed to generate unique slugs for Mongoose documents, but in my testing, I've found that non-unique slugs are being generated under certain circumstances.

### Steps to Reproduce:

- Create a Mongoose schema with the "mongoose-slugger-plugin" configured.
- Use the plugin to create documents, ensuring that there are potential conflicts in slug generation.
- Observe that in some cases, non-unique slugs are generated, violating the expected behavior.
### Expected Behavior:
I expect the "mongoose-slugger-plugin" to consistently generate unique slugs for Mongoose documents, even when conflicts exist.

### Actual Behavior:
Non-unique slugs are generated in some cases, leading to slug collisions.

### Additional Information:

- I have configured the plugin according to the provided usage instructions.
- This issue occurs intermittently and is not consistently reproducible, making it challenging to pinpoint the exact cause.
- I'm using the latest version of the "mongoose-slugger-plugin"
- I have attached a code snippet of my schema and plugin configuration for reference.
```js
import mongoose from "mongoose";
import { sluggerPlugin } from "mongoose-slugger-plugin";

const { Schema, model } = mongoose;

const schema = new Schema<any>(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      ref: "User",
    },
    title: {
      type: String,
      required: true,
    },
    slug: {
      type: String,
      unique: true,
      require: true,
    },
    description: {
      type: String,
    },
    assets: {
      type: [{ type: String, required: true }],
      validate: {
        validator: function (items: []) {
          return items && items.length > 0;
        },
        message: "At least one asset is required",
      },
    },
  },
  { timestamps: true }
);

schema.index(
  { slug: 1, title: 1, description: 1 },
  { name: "search", unique: true }
);

schema.plugin(sluggerPlugin, {
  slugPath: "slug",
  generateFrom: ["title"],
  index: "search",
});
```
### Environment:

- Node.js version: 19.8.1
- Mongoose version: 7.5.1
- Operating System: macOs

Please let me know if you need any additional information to investigate this issue.

**Comment by qqilihq** [comment]
Hi Nziranziza,

the `description` should probably not be part of the unique index.

-Philipp
